import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CursorGlow from "@/components/CursorGlow";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Altalya | Transforming hands into minds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white relative overflow-x-hidden">

        {/* GLOBAL BACKGROUND */}
        <div className="fixed inset-0 -z-10">
    
        {/* Gradient */}
        <div className="absolute inset-0 bg-gradient-to-br from-black via-gray-900 to-black" />

        {/* Glow Effects */}
        <div className="absolute w-[600px] h-[600px] bg-purple-500/20 blur-3xl rounded-full top-[-100px] left-[-100px]" />
        <div className="absolute w-[500px] h-[500px] bg-blue-500/20 blur-3xl rounded-full bottom-[-100px] right-[-100px]" />

        </div>
        <CursorGlow />
        {children}
      </body>
    </html>
  );
}
